# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

group = eu.minemania
mod_id = watson
mod_name = Watson
author = Annevdl29
mod_file_name = watson-fabric
project_slug = watson
modrinth_debug = false

# Current mod version
mod_version = 1.17.0

# Required malilib version
malilib_version = 0.28.1
malilib_mod_version = >=0.28.1

# Minecraft, Fabric and mappings versions
minecraft_version_malilib = 26.1
minecraft_version_mod = 26.1
minecraft_version = 26.1
minecraft_version_dependency = >=26.1 <=26.1.2

fabric_loader_version = 0.18.4
fabric_api_version = 0.145.1+26.1
mod_menu_version = 18.0.0-alpha.8
loom_version = 1.15.+
