#!/usr/bin/env python3
"""Migrate Watson from Yarn 1.21.3 mappings to Mojang 26.1 mappings."""
import re
from pathlib import Path

REPLACEMENTS = [
    # Imports - longest first
    ("import net.minecraft.text.TranslatableTextContent;", "import net.minecraft.network.chat.contents.TranslatableContents;"),
    ("import net.minecraft.text.MutableText;", "import net.minecraft.network.chat.MutableComponent;"),
    ("import net.minecraft.text.HoverEvent;", "import net.minecraft.network.chat.HoverEvent;"),
    ("import net.minecraft.text.Style;", "import net.minecraft.network.chat.Style;"),
    ("import net.minecraft.text.Text;", "import net.minecraft.network.chat.Component;"),
    ("import net.minecraft.text.*;", "import net.minecraft.network.chat.*;"),
    ("import net.minecraft.client.MinecraftClient;", "import net.minecraft.client.Minecraft;"),
    ("import net.minecraft.client.network.ClientPlayerEntity;", "import net.minecraft.client.player.LocalPlayer;"),
    ("import net.minecraft.client.network.ClientPlayNetworkHandler;", "import net.minecraft.client.multiplayer.ClientPacketListener;"),
    ("import net.minecraft.client.network.ServerInfo;", "import net.minecraft.client.multiplayer.ServerData;"),
    ("import net.minecraft.client.network.ClientConnectionState;", "import net.minecraft.client.multiplayer.CommonListenerCookie;"),
    ("import net.minecraft.client.world.ClientWorld;", "import net.minecraft.client.multiplayer.ClientLevel;"),
    ("import net.minecraft.entity.player.PlayerEntity;", "import net.minecraft.world.entity.player.Player;"),
    ("import net.minecraft.entity.LivingEntity;", "import net.minecraft.world.entity.LivingEntity;"),
    ("import net.minecraft.entity.EntityType;", "import net.minecraft.world.entity.EntityType;"),
    ("import net.minecraft.entity.Entity;", "import net.minecraft.world.entity.Entity;"),
    ("import net.minecraft.entity.decoration.painting.PaintingEntity;", "import net.minecraft.world.entity.decoration.Painting;"),
    ("import net.minecraft.server.command.ServerCommandSource;", "import net.minecraft.commands.CommandSourceStack;"),
    ("import net.minecraft.server.command.CommandManager;", "import net.minecraft.commands.Commands;"),
    ("import net.minecraft.server.command.CommandOutput;", "import net.minecraft.commands.CommandResultCallback;"),
    ("import net.minecraft.command.CommandSource;", "import net.minecraft.commands.CommandSource;"),
    ("import net.minecraft.command.ISuggestionProvider;", "import net.minecraft.commands.SharedSuggestionProvider;"),
    ("import net.minecraft.command.argument.EntityAnchorArgumentType;", "import net.minecraft.commands.arguments.EntityAnchorArgument;"),
    ("import static net.minecraft.server.command.CommandManager.literal;", "import static net.minecraft.commands.Commands.literal;"),
    ("import static net.minecraft.server.command.CommandManager.argument;", "import static net.minecraft.commands.Commands.argument;"),
    ("import static net.minecraft.command.argument.BlockPosArgumentType.blockPos;", "import static net.minecraft.commands.arguments.coordinates.BlockPosArgument.blockPos;"),
    ("import static net.minecraft.command.argument.BlockPosArgumentType.getBlockPos;", "import static net.minecraft.commands.arguments.coordinates.BlockPosArgument.getBlockPos;"),
    ("import net.minecraft.util.Identifier;", "import net.minecraft.resources.Identifier;"),
    ("import net.minecraft.util.Formatting;", "import net.minecraft.ChatFormatting;"),
    ("import net.minecraft.util.math.BlockPos;", "import net.minecraft.core.BlockPos;"),
    ("import net.minecraft.util.math.Vec3d;", "import net.minecraft.world.phys.Vec3;"),
    ("import net.minecraft.util.math.MathHelper;", "import net.minecraft.util.Mth;"),
    ("import net.minecraft.util.math.random.Random;", "import net.minecraft.util.RandomSource;"),
    ("import net.minecraft.util.profiler.Profiler;", "import net.minecraft.util.profiling.ProfilerFiller;"),
    ("import net.minecraft.registry.Registries;", "import net.minecraft.core.registries.BuiltInRegistries;"),
    ("import net.minecraft.registry.RegistryKey;", "import net.minecraft.resources.ResourceKey;"),
    ("import net.minecraft.registry.tag.EntityTypeTags;", "import net.minecraft.tags.EntityTypeTags;"),
    ("import net.minecraft.world.World;", "import net.minecraft.world.level.Level;"),
    ("import net.minecraft.network.PacketByteBuf;", "import net.minecraft.network.FriendlyByteBuf;"),
    ("import net.minecraft.network.packet.CustomPayload;", "import net.minecraft.network.protocol.common.custom.CustomPacketPayload;"),
    ("import net.minecraft.network.codec.PacketCodec;", "import net.minecraft.network.codec.StreamCodec;"),
    ("import net.minecraft.network.ClientConnection;", "import net.minecraft.network.Connection;"),
    ("import net.minecraft.network.packet.c2s.play.ClientCommandC2SPacket;", "import net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket;"),
    ("import net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket;", "import net.minecraft.network.protocol.game.ServerboundMovePlayerPacket;"),
    ("import net.minecraft.network.packet.s2c.play.CommandTreeS2CPacket;", "import net.minecraft.network.protocol.game.ClientboundCommandsPacket;"),
    ("import net.minecraft.block.BlockState;", "import net.minecraft.world.level.block.state.BlockState;"),
    ("import net.minecraft.block.Blocks;", "import net.minecraft.world.level.block.Blocks;"),
    ("import net.minecraft.block.Block;", "import net.minecraft.world.level.block.Block;"),
    ("import net.minecraft.block.*;", "import net.minecraft.world.level.block.*;"),
    ("import net.minecraft.item.SpawnEggItem;", "import net.minecraft.world.item.SpawnEggItem;"),
    ("import net.minecraft.item.ItemStack;", "import net.minecraft.world.item.ItemStack;"),
    ("import net.minecraft.item.Items;", "import net.minecraft.world.item.Items;"),
    ("import net.minecraft.item.Item;", "import net.minecraft.world.item.Item;"),
    ("import net.minecraft.nbt.StringNbtReader;", "import net.minecraft.nbt.TagParser;"),
    ("import net.minecraft.nbt.NbtCompound;", "import net.minecraft.nbt.CompoundTag;"),
    ("import net.minecraft.component.type.NbtComponent;", "import net.minecraft.world.item.component.CustomData;"),
    ("import net.minecraft.component.DataComponentTypes;", "import net.minecraft.core.component.DataComponents;"),
    ("import net.minecraft.sound.SoundEvent;", "import net.minecraft.sounds.SoundEvent;"),
    ("import net.minecraft.client.gui.hud.ChatHud;", "import net.minecraft.client.gui.components.ChatComponent;"),
    ("import net.minecraft.client.gui.screen.ChatInputSuggestor;", "import net.minecraft.client.gui.screens.ChatScreen.ChatSuggestionProvider;"),
    ("import net.minecraft.client.gui.screen.Screen;", "import net.minecraft.client.gui.screens.Screen;"),
    ("import net.minecraft.client.gui.widget.TextFieldWidget;", "import net.minecraft.client.gui.components.EditBox;"),
    ("import net.minecraft.client.gui.DrawContext;", "import net.minecraft.client.gui.GuiGraphics;"),
    ("import net.minecraft.client.util.math.MatrixStack;", "import com.mojang.blaze3d.vertex.PoseStack;"),
    ("import net.minecraft.client.util.ScreenshotRecorder;", "import net.minecraft.client.Screenshot;"),
    ("import net.minecraft.client.texture.NativeImage;", "import com.mojang.blaze3d.platform.NativeImage;"),
    ("import net.minecraft.client.render.Camera;", "import net.minecraft.client.Camera;"),
    ("import net.minecraft.client.render.Frustum;", "import net.minecraft.client.renderer.culling.Frustum;"),
    ("import net.minecraft.client.render.BufferBuilder;", "import com.mojang.blaze3d.vertex.BufferBuilder;"),
    ("import net.minecraft.client.render.BufferRenderer;", "import com.mojang.blaze3d.vertex.BufferUploader;"),
    ("import net.minecraft.client.render.BuiltBuffer;", "import com.mojang.blaze3d.vertex.MeshData;"),
    ("import net.minecraft.client.render.Tessellator;", "import com.mojang.blaze3d.vertex.Tesselator;"),
    ("import net.minecraft.client.render.block.BlockRenderManager;", "import net.minecraft.client.renderer.block.BlockRenderDispatcher;"),
    ("import net.minecraft.client.render.model.BakedModel;", "import net.minecraft.client.resources.model.BakedModel;"),
    ("import net.minecraft.client.render.model.BakedQuad;", "import net.minecraft.client.renderer.block.model.BakedQuad;"),
    ("import net.minecraft.client.gl.ShaderProgramKeys;", "import net.minecraft.client.renderer.ShaderProgramKeys;"),
    ("import net.minecraft.client.render.*;", "import net.minecraft.client.renderer.*;\nimport com.mojang.blaze3d.vertex.*;"),
    ("import net.minecraft.util.math.*;", "import net.minecraft.core.*;\nimport net.minecraft.world.phys.*;"),
    ("import net.minecraft.scoreboard.Team;", "import net.minecraft.world.scores.PlayerTeam;"),
    # Types / identifiers
    ("MutableText", "MutableComponent"),
    ("TranslatableTextContent", "TranslatableContents"),
    ("MinecraftClient", "Minecraft"),
    ("ClientPlayerEntity", "LocalPlayer"),
    ("ClientPlayNetworkHandler", "ClientPacketListener"),
    ("ServerInfo", "ServerData"),
    ("ClientWorld", "ClientLevel"),
    ("PlayerEntity", "Player"),
    ("ServerCommandSource", "CommandSourceStack"),
    ("PacketByteBuf", "FriendlyByteBuf"),
    ("NbtCompound", "CompoundTag"),
    ("NbtComponent", "CustomData"),
    ("DataComponentTypes", "DataComponents"),
    ("ChatHud", "ChatComponent"),
    ("DrawContext", "GuiGraphics"),
    ("MatrixStack", "PoseStack"),
    ("Formatting", "ChatFormatting"),
    ("PaintingEntity", "Painting"),
    ("ClientCommandC2SPacket", "ServerboundPlayerCommandPacket"),
    ("PlayerMoveC2SPacket", "ServerboundMovePlayerPacket"),
    ("CommandTreeS2CPacket", "ClientboundCommandsPacket"),
    ("TextFieldWidget", "EditBox"),
    ("ChatInputSuggestor", "ChatScreen.ChatSuggestionProvider"),
    ("Registries", "BuiltInRegistries"),
    ("RegistryKey<World>", "ResourceKey<Level>"),
    ("Set<RegistryKey<World>>", "Set<ResourceKey<Level>>"),
    ("Profiler", "ProfilerFiller"),
    ("Random", "RandomSource"),
    ("BuiltBuffer", "MeshData"),
    ("Tessellator", "Tesselator"),
    ("BlockRenderManager", "BlockRenderDispatcher"),
    ("Team", "PlayerTeam"),
    ("Vec3d", "Vec3"),
    ("MathHelper", "Mth"),
    ("ClientConnectionState", "CommonListenerCookie"),
    ("ClientConnection", "Connection"),
    ("PacketCodec", "StreamCodec"),
    ("ScreenshotRecorder", "Screenshot"),
    # CustomPayload API
    ("implements CustomPayload", "implements CustomPacketPayload"),
    ("CustomPayload.Id<", "CustomPacketPayload.Type<"),
    ("CustomPayload.codecOf", "CustomPacketPayload.codec"),
    ("CustomPayload.codec", "CustomPacketPayload.codec"),
    ("Id<Payload>", "Type<Payload>"),
    ("new Id<>(", "new Type<>(Payload::new, "),
    ("getId()", "type()"),
    # Methods / fields
    ("MinecraftClient.getInstance()", "Minecraft.getInstance()"),
    (".getNetworkHandler()", ".getConnection()"),
    (".getWorld()", ".level()"),
    (".getPlayer()", ".player()"),
    ("Text.literal(", "Component.literal("),
    ("Text.of(", "Component.literal("),
    ("MutableText.of(", "MutableComponent.create("),
    ("StringNbtReader.parse(", "TagParser.parseTag("),
    ("NbtComponent.of(", "CustomData.of("),
    ("ClientCommandC2SPacket.Mode", "ServerboundPlayerCommandPacket.Action"),
    ("Registries.BLOCK", "BuiltInRegistries.BLOCK"),
    ("Registries.ITEM", "BuiltInRegistries.ITEM"),
    ("Registries.ENTITY_TYPE", "BuiltInRegistries.ENTITY_TYPE"),
    # Text as type - careful, do after Text.literal
    (" Text ", " Component "),
    ("<Text>", "<Component>"),
    ("(Text ", "(Component "),
    (", Text", ", Component"),
    (" Text,", " Component,"),
    (" Text)", " Component)"),
    ("extends Text", "extends Component"),
]

def migrate_file(path: Path) -> None:
    content = path.read_text(encoding="utf-8")
    original = content
    for old, new in REPLACEMENTS:
        content = content.replace(old, new)
    if content != original:
        path.write_text(content, encoding="utf-8")

for java_file in Path("src").rglob("*.java"):
    migrate_file(java_file)

# Update mixin config
mixins = Path("src/main/resources/mixins.watson.json")
if mixins.exists():
    mixins.write_text(mixins.read_text().replace("JAVA_17", "JAVA_25"), encoding="utf-8")

print("Migration complete")
